# Generated by Django 5.2.6 on 2025-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_useremailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailnotification',
            name='joined_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useremailnotification',
            name='joined_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
