# Generated by Django 5.2.6 on 2025-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_useremailnotification_joined_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailnotification',
            name='deadline_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useremailnotification',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
